name: sam-env
channels:
  - conda-forge
  - bioconda
  - https://repo.continuum.io/pkgs/free
  - anaconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.6.2=py36h516909a_0
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.3=py_1
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - bcftools=1.9=ha228f0b_4
  - bcrypt=3.1.7=py36h8c4c3a4_1
  - bedtools=2.27.1=he513fc3_4
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - brotlipy=0.7.0=py36h8c4c3a4_1000
  - bwa=0.7.17=hed695b0_7
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.16.1=h516909a_0
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.14.1=py36h0ff685e_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=3.0=py36h45558ae_0
  - curl=7.71.1=he644dc0_4
  - cython=0.29.21=py36h831f99a_0
  - docutils=0.16=py36h9f0ad1d_1
  - dropbox=10.1.1=pyh9f0ad1d_0
  - fastqc=0.11.6=2
  - fastx_toolkit=0.0.14=0
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.13.1=h1056068_1002
  - freebayes=1.3.2=py36ha64edc8_2
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - ftputil=4.0.0=py_0
  - future=0.18.2=py36h9f0ad1d_1
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_9
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - graphite2=1.3.13=he1b5a44_1001
  - gsl=2.6=h294904e_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - harfbuzz=2.4.0=hee91db6_5
  - htslib=1.9=h4da6232_3
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - idna_ssl=1.1.0=py36_1000
  - jpeg=9d=h516909a_0
  - krb5=1.17.1=hfafb76e_2
  - last=876=py36_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_4
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20191231=h46ee950_1
  - libev=4.33=h516909a_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h24d8f2e_14
  - libgfortran-ng=7.5.0=hdf63c60_14
  - libgomp=9.3.0=h24d8f2e_14
  - libgtextutils=0.7=he1b5a44_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=17_openblas
  - libnghttp2=1.41.0=hab1572f_1
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_14
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h72b56ed_2
  - lz4-c=1.9.2=he1b5a44_1
  - make=4.3=h516909a_0
  - multidict=4.7.5=py36h8c4c3a4_1
  - ncurses=6.1=hf484d3e_1002
  - nose=1.3.7=py36h9f0ad1d_1004
  - numpy=1.19.1=py36h7314795_0
  - openjdk=11.0.8=hacce0ff_0
  - openssl=1.1.1g=h516909a_1
  - pandas=1.1.0=py36h831f99a_0
  - pango=1.42.4=h7062337_4
  - parallel=20200722=0
  - paramiko=2.7.1=pyh9f0ad1d_1
  - pcre=8.44=he1b5a44_0
  - pcre2=10.35=h2f06484_0
  - perl=5.26.2=h516909a_1006
  - picard=2.18.0=py36_0
  - pip=20.2.2=py_0
  - pixman=0.38.0=h516909a_1003
  - psutil=5.7.2=py36h8c4c3a4_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pynacl=1.3.0=py36h516909a_1001
  - pyopenssl=19.1.0=py_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10=h8356626_1011_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - r-assertthat=0.2.1=r40h6115d3f_2
  - r-backports=1.1.8=r40hcdcec82_0
  - r-base=4.0.2=he766273_1
  - r-boot=1.3_25=r40h6115d3f_1
  - r-broom=0.7.0=r40h6115d3f_0
  - r-callr=3.4.3=r40h6115d3f_1
  - r-circlize=0.4.9=r40h6115d3f_1
  - r-cli=2.0.2=r40h6115d3f_1
  - r-colorspace=1.4_1=r40hcdcec82_2
  - r-cowplot=1.0.0=r40h6115d3f_2
  - r-crayon=1.3.4=r40h6115d3f_1003
  - r-data.table=1.12.8=r40hcdcec82_1
  - r-deriv=4.0=r40h6115d3f_1
  - r-desc=1.2.0=r40h6115d3f_1003
  - r-digest=0.6.25=r40h0357c0b_2
  - r-doby=4.6.7=r40h6115d3f_0
  - r-dplyr=1.0.1=r40h0357c0b_0
  - r-ellipsis=0.3.1=r40hcdcec82_0
  - r-evaluate=0.14=r40h6115d3f_2
  - r-fansi=0.4.1=r40hcdcec82_1
  - r-farver=2.0.3=r40h0357c0b_1
  - r-generics=0.0.2=r40h6115d3f_1003
  - r-ggplot2=3.3.2=r40h6115d3f_0
  - r-globaloptions=0.1.2=r40_0
  - r-glue=1.4.1=r40hcdcec82_0
  - r-gtable=0.3.0=r40h6115d3f_3
  - r-isoband=0.2.2=r40h0357c0b_0
  - r-labeling=0.3=r40h6115d3f_1003
  - r-lattice=0.20_41=r40hcdcec82_2
  - r-lifecycle=0.2.0=r40h6115d3f_1
  - r-lme4=1.1_23=r40h0357c0b_1
  - r-magrittr=1.5=r40h6115d3f_1003
  - r-mass=7.3_51.6=r40hcdcec82_2
  - r-matrix=1.2_18=r40h7fa42b6_3
  - r-mgcv=1.8_31=r40h7fa42b6_1
  - r-minqa=1.2.4=r40h6786f55_1005
  - r-misc3d=0.8_4=r40_2003
  - r-munsell=0.5.0=r40h6115d3f_1003
  - r-nlme=3.1_148=r40h9bbef5b_0
  - r-nloptr=1.2.2.2=r40h0357c0b_0
  - r-pbkrtest=0.4_8.6=r40h6115d3f_0
  - r-pillar=1.4.6=r40h6115d3f_0
  - r-pkgbuild=1.1.0=r40h6115d3f_0
  - r-pkgconfig=2.0.3=r40h6115d3f_1
  - r-pkgload=1.1.0=r40h0357c0b_0
  - r-plot3d=1.3=r40_1
  - r-plyr=1.8.6=r40h0357c0b_1
  - r-praise=1.0.0=r40h6115d3f_1004
  - r-prettyunits=1.1.1=r40h6115d3f_1
  - r-processx=3.4.3=r40hcdcec82_0
  - r-ps=1.3.4=r40hcdcec82_0
  - r-purrr=0.3.4=r40hcdcec82_1
  - r-r6=2.4.1=r40h6115d3f_1
  - r-rcolorbrewer=1.1_2=r40h6115d3f_1003
  - r-rcpp=1.0.4.6=r40h0357c0b_1
  - r-rcppeigen=0.3.3.7.0=r40h51c796c_2
  - r-reshape2=1.4.4=r40h0357c0b_1
  - r-rlang=0.4.7=r40hcdcec82_0
  - r-rprojroot=1.3_2=r40h6115d3f_1003
  - r-rstudioapi=0.11=r40h6115d3f_1
  - r-scales=1.1.1=r40h6115d3f_0
  - r-shape=1.4.4=r40_1003
  - r-statmod=1.4.34=r40h6e990d7_1
  - r-stringi=1.4.6=r40h604b29c_3
  - r-stringr=1.4.0=r40h6115d3f_2
  - r-testthat=2.3.2=r40h0357c0b_1
  - r-tibble=3.0.3=r40hcdcec82_0
  - r-tidyr=1.1.1=r40h0357c0b_1
  - r-tidyselect=1.1.0=r40h6115d3f_0
  - r-utf8=1.1.4=r40hcdcec82_1003
  - r-vctrs=0.3.2=r40hcdcec82_0
  - r-viridislite=0.3.0=r40h6115d3f_1003
  - r-withr=2.2.0=r40h6115d3f_1
  - r-zeallot=0.1.0=r40h6115d3f_1002
  - ratelimiter=1.2.0=py36h9f0ad1d_1001
  - readline=8.0=h46ee950_1
  - requests=2.24.0=pyh9f0ad1d_0
  - samtools=1.9=h10a08f8_12
  - sed=4.8=hbfbb72e_0
  - setuptools=49.3.2=py36h9f0ad1d_0
  - six=1.15.0=pyh9f0ad1d_0
  - snakemake=4.4.0=py36_0
  - sqlite=3.32.3=hcee41ef_1
  - tabix=0.2.6=ha92aebf_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - trimmomatic=0.36=6
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - vcftools=0.1.15=he941832_2
  - wheel=0.34.2=py_1
  - wrapt=1.12.1=py36h8c4c3a4_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.11=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.4.2=py36h516909a_0
  - zlib=1.2.11=h516909a_1007
  - zstd=1.4.5=h6597ccf_2
prefix: /home/bella/miniconda3/envs/sam-env

